experiment_name: "masked_without_saliency_network"

seed: 2023
max_epochs: 2000
gradient_clip_val: 0
batch_frequency: 1000
img_batch_frequency: 100
sample_intermediates: True
log_imgs_ds_factor: 1.0

model:
  target: vle.masked_ae3.AutoEncoder
  params: 
    max_tokens: 4
    min_tokens: 2
    update_token_dist_step: 500

    learning_rate: 1e-3
    use_p_loss: False
    p_mult: 1e-1
    mask_mult: 1.0
  
    encoder:
      target: vle.modules.MemoryEncoder
      params:
        img_channels: 4
        base_channels: 32
        latent_channels: 4
        num_res_blocks: 4
        num_groups: 1
        channel_mults:
          - 1
          - 2
          - 4
          - 4

        memory_network:
          target: vle.modules.memory.ConvLSTM
          params:
            n_layers: 1
            input_channels: 32
            hidden_channels: 64
            use_token_embedder: False
        
    decoder:
      target: vle.modules.Decoder
      params:
        img_channels: 4
        base_channels: 32
        latent_channels: 4
        num_res_blocks: 4
        num_groups: 1
        channel_mults:
          - 1
          - 2
          - 4
          - 4


data:
  target: vle.data.laion.WebDataModuleFromConfig
  params:
    tar_base: "pipe:aws s3 cp --quiet s3://runway-research-datasets/laion/improved_aesthetics_4.75plus/"

    min_size: 512
    max_pwatermark: 0.4999

    batch_size: 3
    num_workers: 8
    multinode: True

    partitions:
      train:
        shards: '{000000..098853}.tar -'
        shuffle: 10000
        image_key: jpg

    custom_batcher:
      target: vle.data.batcher.AspectRatiosBatcher
      params:
        resolution_constant: 262144 # 512 x 512
        aspect_ratios:
          - [1, 1]
          - [4, 3]
          - [16, 9]
          